export const GET_BLOG_CONTENTS = 'GET_BLOG_CONTENTS';
export const GET_BLOG_CONTENTS_SUCCESS = 'GET_BLOG_CONTENTS_SUCCESS';
export const GET_BLOG_CONTENTS_FAILURE = 'GET_BLOG_CONTENTS_FAILURE';

export const CLEAR_BLOG_CONTENTS = 'CLEAR_BLOG_CONTENTS';
