export const SET_LOGIN_INFO = 'SET_LOGIN_INFO';
export const CLEAR_LOGIN_INFO = 'CLEAR_LOGIN_INFO';
export const EXCUTE_LOGIN = 'EXCUTE_LOGIN';
export const EXCUTE_LOGIN_SUCCESS = 'EXCUTE_LOGIN_SUCCESS';
export const EXCUTE_LOGIN_FAILURE = 'EXCUTE_LOGIN_FAILURE';
